export const ROLE_USER = "ROLE_USER";
export const ROLE_SUPER_ADMIN = "ROLE_SUPER_ADMIN";
export const ROLE_EXAM_MAKER = "ROLE_EXAM_MAKER";

export const PRACTICE_EXAMS = "PRACTICE_EXAMS";
export const ASSIGNED_EXAMS = "ASSIGNED_EXAMS";

export const MANAGE_EXAMS = "MANAGE_EXAMS";
export const MANAGE_USERS = "MANAGE_USERS";
export const MANAGE_TENANTS = "MANAGE_TENANTS";

export const EXAM_TYPE_PRACTICE = "PRACTICE";
export const EXAM_TYPE_ASSIGNED = "ASSIGNED";
export const EXAM_TYPE_ALL = "ALL";

export const ROLES = [
    ROLE_USER,
    ROLE_SUPER_ADMIN,
    ROLE_EXAM_MAKER
];

export const ROLE_BASED_RESOURCES = {
    [ROLE_USER] : [PRACTICE_EXAMS, ASSIGNED_EXAMS],
    [ROLE_SUPER_ADMIN] : [MANAGE_EXAMS, MANAGE_USERS, MANAGE_TENANTS],
    [ROLE_EXAM_MAKER] : [MANAGE_EXAMS]
};

